-- First, let's see which categories already exist and insert only new ones
INSERT INTO public.categories (name, description, icon) VALUES
-- Home & Garden (only new ones)
('Electrical Work', 'Licensed electrical installation, repair, and maintenance services', 'zap'),
('HVAC Services', 'Heating, ventilation, and air conditioning services', 'thermometer'),
('Roofing', 'Roof installation, repair, and maintenance services', 'home'),
('Painting & Decorating', 'Interior and exterior painting and decorating services', 'paintbrush'),
('Landscaping', 'Garden design, lawn care, and outdoor beautification', 'leaf'),
('Carpentry', 'Custom woodwork, furniture making, and structural carpentry', 'hammer'),
('Cleaning Services', 'Professional residential and commercial cleaning', 'sparkles'),
('Pest Control', 'Extermination and prevention of pests and insects', 'bug'),
('Pool Maintenance', 'Swimming pool cleaning, repair, and chemical balancing', 'waves'),
('Garage Door Repair', 'Installation and repair of garage doors and openers', 'garage'),
('Fencing', 'Installation and repair of residential and commercial fencing', 'fence'),
('Gutter Services', 'Gutter installation, cleaning, and repair services', 'droplets'),
('Flooring', 'Installation and repair of various flooring materials', 'square'),
('Kitchen Renovation', 'Complete kitchen remodeling and renovation services', 'chef-hat'),
('Bathroom Renovation', 'Bathroom remodeling and fixture installation', 'bath'),
('Interior Design', 'Professional interior design and space planning', 'palette'),
('Window Installation', 'Window replacement and installation services', 'square'),
('Driveway & Paving', 'Concrete, asphalt, and stone driveway installation', 'road'),
('Tile Installation', 'Ceramic, stone, and specialty tile installation', 'grid'),

-- Beauty & Wellness
('Hair Styling', 'Professional hair cutting, coloring, and styling services', 'scissors'),
('Nail Services', 'Manicures, pedicures, and nail art services', 'sparkles'),
('Makeup Artist', 'Professional makeup for events, weddings, and photography', 'palette'),
('Massage Therapy', 'Therapeutic and relaxation massage services', 'heart'),
('Skincare Treatment', 'Facial treatments and professional skincare services', 'smile'),
('Barber Services', 'Traditional and modern barbering services for men', 'scissors'),
('Eyebrow Threading', 'Professional eyebrow shaping and threading services', 'eye'),
('Spa Services', 'Full-service spa treatments and wellness packages', 'flower'),
('Personal Training', 'One-on-one fitness coaching and workout planning', 'dumbbell'),
('Yoga Instruction', 'Private and group yoga classes and instruction', 'user'),
('Nutrition Counseling', 'Professional dietary advice and meal planning', 'apple'),
('Mental Health Counseling', 'Professional psychological counseling and therapy', 'brain'),
('Physical Therapy', 'Rehabilitation and physical therapy services', 'activity'),
('Chiropractic Care', 'Spinal adjustment and musculoskeletal treatment', 'user'),
('Acupuncture', 'Traditional Chinese medicine and acupuncture treatment', 'target'),

-- Technology & Digital
('Web Development', 'Custom website design and development services', 'monitor'),
('Mobile App Development', 'iOS and Android mobile application development', 'smartphone'),
('Digital Marketing', 'SEO, social media marketing, and online advertising', 'trending-up'),
('Graphic Design', 'Logo design, branding, and visual communication', 'image'),
('Software Development', 'Custom software solutions and programming services', 'code'),
('IT Support', 'Computer repair, network setup, and technical support', 'cpu'),
('Database Management', 'Database design, optimization, and administration', 'database'),
('Cybersecurity', 'Security audits, protection, and risk assessment', 'shield'),
('Cloud Services', 'Cloud migration, setup, and management services', 'cloud'),
('E-commerce Solutions', 'Online store development and e-commerce consulting', 'shopping-cart'),
('Video Editing', 'Professional video editing and post-production services', 'video'),
('Photography', 'Professional photography for events, portraits, and commercial use', 'camera'),
('Voice Over Services', 'Professional voice recording for commercials and media', 'mic'),
('3D Modeling', 'Three-dimensional design and visualization services', 'box'),
('Game Development', 'Video game design and development services', 'gamepad2'),

-- Automotive
('Auto Repair', 'General automotive repair and maintenance services', 'car'),
('Oil Change', 'Quick oil change and basic automotive maintenance', 'droplet'),
('Tire Services', 'Tire installation, rotation, and balancing services', 'circle'),
('Auto Detailing', 'Professional car washing, waxing, and detailing', 'sparkles'),
('Engine Diagnostics', 'Computer diagnostics and engine troubleshooting', 'search'),
('Brake Repair', 'Brake system inspection, repair, and replacement', 'octagon'),
('Transmission Repair', 'Transmission service and repair specialists', 'settings'),
('Auto Body Repair', 'Collision repair and automotive bodywork', 'wrench'),
('Window Tinting', 'Automotive window tinting and film installation', 'eye-off'),
('Car Locksmith', 'Automotive lockout and key replacement services', 'key'),
('Motorcycle Repair', 'Motorcycle maintenance and repair services', 'bike'),
('RV Services', 'Recreational vehicle maintenance and repair', 'truck'),
('Boat Repair', 'Marine vessel maintenance and repair services', 'anchor'),
('Car Audio Installation', 'Automotive sound system installation and upgrade', 'volume-2'),
('Paint Protection', 'Automotive paint protection and ceramic coating', 'shield'),

-- Education & Tutoring
('Math Tutoring', 'Private mathematics instruction and homework help', 'calculator'),
('English Tutoring', 'Language arts, writing, and literature instruction', 'book'),
('Science Tutoring', 'Physics, chemistry, and biology tutoring services', 'flask'),
('Music Lessons', 'Private instruction for various musical instruments', 'music'),
('Language Learning', 'Foreign language instruction and conversation practice', 'globe'),
('Test Preparation', 'SAT, ACT, and standardized test preparation services', 'file-text'),
('Computer Training', 'Basic computer skills and software training', 'monitor'),
('Art Classes', 'Drawing, painting, and creative arts instruction', 'palette'),
('Dance Lessons', 'Private and group dance instruction', 'music'),
('Driving Instruction', 'Professional driving lessons and road test preparation', 'car'),
('Career Coaching', 'Professional development and career guidance', 'briefcase'),
('Study Skills', 'Academic coaching and study strategy development', 'book-open'),
('Special Needs Education', 'Specialized tutoring for students with learning differences', 'heart'),
('Early Childhood Education', 'Preschool and kindergarten readiness programs', 'baby'),
('Adult Education', 'GED preparation and adult learning programs', 'graduation-cap'),

-- Business Services
('Accounting', 'Bookkeeping, tax preparation, and financial services', 'calculator'),
('Legal Services', 'Legal consultation and representation services', 'scale'),
('Marketing Consulting', 'Business marketing strategy and consultation', 'trending-up'),
('Business Planning', 'Business plan development and startup consulting', 'file-text'),
('HR Consulting', 'Human resources and employee management services', 'users'),
('Financial Planning', 'Investment advice and financial planning services', 'dollar-sign'),
('Real Estate Services', 'Property buying, selling, and management services', 'home'),
('Insurance Services', 'Insurance consultation and policy management', 'shield'),
('Translation Services', 'Document translation and interpretation services', 'globe'),
('Event Planning', 'Corporate and personal event planning services', 'calendar'),
('Public Relations', 'PR strategy and reputation management services', 'megaphone'),
('Grant Writing', 'Grant application and proposal writing services', 'pen-tool'),
('Virtual Assistant', 'Administrative support and virtual office services', 'user'),
('Data Entry', 'Professional data entry and database management', 'keyboard'),
('Research Services', 'Market research and business intelligence services', 'search'),

-- Food & Catering
('Personal Chef', 'Private cooking and meal preparation services', 'chef-hat'),
('Catering Services', 'Event catering and food service management', 'utensils'),
('Baking Services', 'Custom cakes, pastries, and baked goods', 'cake'),
('Meal Prep', 'Healthy meal preparation and delivery services', 'apple'),
('Bartending', 'Professional bartending services for events', 'wine'),
('Food Delivery', 'Restaurant and grocery delivery services', 'truck'),
('Nutrition Planning', 'Custom diet plans and nutritional guidance', 'heart'),
('Cooking Lessons', 'Private cooking instruction and culinary classes', 'chef-hat'),
('Wine Consultation', 'Wine selection and sommelier services', 'wine'),
('Coffee Services', 'Mobile coffee cart and barista services', 'coffee'),
('Specialty Diets', 'Specialized meal preparation for dietary restrictions', 'leaf'),
('Restaurant Consulting', 'Restaurant business and menu development consulting', 'utensils'),
('Food Photography', 'Professional food styling and photography', 'camera'),
('Kitchen Equipment', 'Commercial kitchen equipment sales and service', 'wrench'),
('Farmers Market', 'Local produce and artisanal food products', 'apple'),

-- Pet Care
('Pet Grooming', 'Professional pet bathing, grooming, and styling', 'scissors'),
('Dog Walking', 'Daily dog walking and exercise services', 'heart'),
('Pet Sitting', 'In-home pet care and overnight sitting services', 'home'),
('Veterinary Care', 'Medical care and health services for pets', 'heart'),
('Pet Training', 'Obedience training and behavioral modification', 'zap'),
('Pet Photography', 'Professional pet portraits and photography', 'camera'),
('Pet Boarding', 'Overnight care and boarding facilities for pets', 'home'),
('Pet Transportation', 'Safe transportation services for pets', 'car'),
('Aquarium Services', 'Fish tank setup, maintenance, and cleaning', 'fish'),
('Exotic Pet Care', 'Specialized care for reptiles, birds, and exotic pets', 'bug'),
('Pet Waste Removal', 'Yard cleanup and pet waste management services', 'trash'),
('Pet Supplies', 'Premium pet food, toys, and accessory sales', 'shopping-bag'),
('Animal Behavior', 'Pet psychology and behavioral consultation', 'brain'),
('Pet Insurance', 'Pet health insurance and coverage consultation', 'shield'),
('Pet Adoption', 'Animal rescue and pet adoption services', 'heart'),

-- Transportation & Logistics
('Moving Services', 'Residential and commercial moving and packing', 'truck'),
('Courier Services', 'Package delivery and messenger services', 'package'),
('Taxi Services', 'Local transportation and taxi services', 'car'),
('Ride Sharing', 'Personal transportation and ride-sharing services', 'users'),
('Freight Services', 'Commercial shipping and freight transportation', 'truck'),
('Storage Solutions', 'Self-storage and warehouse services', 'archive'),
('Logistics Consulting', 'Supply chain and logistics optimization', 'truck'),
('Equipment Rental', 'Tool and equipment rental services', 'wrench'),
('Junk Removal', 'Waste removal and cleanup services', 'trash'),
('Delivery Services', 'Local and long-distance delivery services', 'package'),
('Airport Shuttle', 'Airport transportation and shuttle services', 'plane'),
('Boat Transportation', 'Marine vessel transport and logistics', 'anchor'),
('International Shipping', 'Global shipping and customs services', 'globe'),
('Vehicle Towing', 'Emergency towing and roadside assistance', 'truck'),
('Packaging Services', 'Professional packing and crating services', 'package'),

-- Entertainment & Events
('DJ Services', 'Professional DJ and music services for events', 'music'),
('Photography Services', 'Event, wedding, and portrait photography', 'camera'),
('Videography', 'Professional video recording and production', 'video'),
('Live Music', 'Musicians and bands for events and entertainment', 'music'),
('Magic Shows', 'Professional magicians and entertainment performers', 'sparkles'),
('Face Painting', 'Children''s party face painting and body art', 'palette'),
('Balloon Art', 'Balloon twisting and decoration services', 'circle'),
('Clown Services', 'Professional clowns and children''s entertainers', 'smile'),
('Karaoke Services', 'Karaoke equipment rental and hosting services', 'mic'),
('Photo Booth', 'Photo booth rental and setup for events', 'camera'),
('Event Decoration', 'Party and event decoration and setup services', 'gift'),
('Wedding Planning', 'Complete wedding planning and coordination', 'heart'),
('Birthday Parties', 'Children''s and adult birthday party planning', 'cake'),
('Corporate Events', 'Business event planning and management', 'briefcase'),
('Holiday Events', 'Seasonal and holiday event planning services', 'gift'),

-- Health & Medical
('Medical Consultation', 'Telemedicine and remote medical consultation', 'stethoscope'),
('Dental Services', 'General dentistry and oral health services', 'smile'),
('Vision Care', 'Eye exams and vision correction services', 'eye'),
('Hearing Care', 'Hearing tests and hearing aid services', 'ear'),
('Lab Services', 'Medical testing and laboratory services', 'flask'),
('Home Healthcare', 'In-home nursing and medical care services', 'home'),
('Medical Equipment', 'Medical device sales and rental services', 'activity'),
('Pharmacy Services', 'Prescription delivery and pharmaceutical services', 'pill'),
('Mental Health', 'Counseling and psychological support services', 'brain'),
('Addiction Recovery', 'Substance abuse treatment and recovery support', 'heart'),
('Pain Management', 'Chronic pain treatment and management services', 'zap'),
('Sleep Medicine', 'Sleep disorder diagnosis and treatment', 'moon'),
('Dermatology', 'Skin care and dermatological services', 'sun'),
('Cardiology', 'Heart health and cardiovascular services', 'heart'),
('Orthopedics', 'Bone and joint health services', 'activity')
ON CONFLICT (name) DO NOTHING;