// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkuwkuixwlibicaelchc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrdXdrdWl4d2xpYmljYWVsY2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNzc3NzcsImV4cCI6MjA2Njc1Mzc3N30.bh8ibevpB87-fVcju4JJA90mrv5g1Yb2Fu4PEX_LMRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);